// Generated by: pnpm db:generate
// DO NOT EDIT MANUALLY — regenerate with pnpm db:generate
//
// This is a placeholder file that will be overwritten when
// `pnpm db:generate` runs against the live Supabase schema.
// The types below are hand-written to match schema.sql and
// unblock downstream builds without Supabase CLI access.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      sources: {
        Row: {
          id: string;
          type: string;
          identifier: string;
          config: Json;
          last_polled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          identifier: string;
          config?: Json;
          last_polled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          identifier?: string;
          config?: Json;
          last_polled_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      posts: {
        Row: {
          id: string;
          source_id: string;
          external_id: string;
          url: string;
          title: string | null;
          body: string | null;
          author: string | null;
          posted_at: string | null;
          tier0_passed: boolean | null;
          tier1_result: Json | null;
          tier2_result: Json | null;
          pipeline_status: string;
          error_detail: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_id: string;
          external_id: string;
          url: string;
          title?: string | null;
          body?: string | null;
          author?: string | null;
          posted_at?: string | null;
          tier0_passed?: boolean | null;
          tier1_result?: Json | null;
          tier2_result?: Json | null;
          pipeline_status?: string;
          error_detail?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_id?: string;
          external_id?: string;
          url?: string;
          title?: string | null;
          body?: string | null;
          author?: string | null;
          posted_at?: string | null;
          tier0_passed?: boolean | null;
          tier1_result?: Json | null;
          tier2_result?: Json | null;
          pipeline_status?: string;
          error_detail?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      offers: {
        Row: {
          id: string;
          destination_url: string;
          destination_url_hash: string;
          title: string;
          description: string | null;
          brand: string | null;
          category: string | null;
          offer_type: string | null;
          shipping_cost: number | null;
          restrictions: string[] | null;
          embedding: string | null;
          status: string;
          last_verified_at: string | null;
          next_check_at: string | null;
          extraction_confidence: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          destination_url: string;
          destination_url_hash: string;
          title: string;
          description?: string | null;
          brand?: string | null;
          category?: string | null;
          offer_type?: string | null;
          shipping_cost?: number | null;
          restrictions?: string[] | null;
          embedding?: string | null;
          status?: string;
          last_verified_at?: string | null;
          next_check_at?: string | null;
          extraction_confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          destination_url?: string;
          destination_url_hash?: string;
          title?: string;
          description?: string | null;
          brand?: string | null;
          category?: string | null;
          offer_type?: string | null;
          shipping_cost?: number | null;
          restrictions?: string[] | null;
          embedding?: string | null;
          status?: string;
          last_verified_at?: string | null;
          next_check_at?: string | null;
          extraction_confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      post_offers: {
        Row: {
          post_id: string;
          offer_id: string;
          created_at: string;
        };
        Insert: {
          post_id: string;
          offer_id: string;
          created_at?: string;
        };
        Update: {
          post_id?: string;
          offer_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      verification_log: {
        Row: {
          id: string;
          offer_id: string;
          checked_at: string;
          http_status: number | null;
          is_live: boolean;
          dead_signals: string[] | null;
          raw_response: string | null;
        };
        Insert: {
          id?: string;
          offer_id: string;
          checked_at?: string;
          http_status?: number | null;
          is_live: boolean;
          dead_signals?: string[] | null;
          raw_response?: string | null;
        };
        Update: {
          id?: string;
          offer_id?: string;
          checked_at?: string;
          http_status?: number | null;
          is_live?: boolean;
          dead_signals?: string[] | null;
          raw_response?: string | null;
        };
        Relationships: [];
      };
      human_review_queue: {
        Row: {
          id: string;
          post_id: string;
          tier2_result: Json;
          confidence: number;
          reviewer_id: string | null;
          decision: string | null;
          review_note: string | null;
          created_at: string;
          reviewed_at: string | null;
        };
        Insert: {
          id?: string;
          post_id: string;
          tier2_result: Json;
          confidence: number;
          reviewer_id?: string | null;
          decision?: string | null;
          review_note?: string | null;
          created_at?: string;
          reviewed_at?: string | null;
        };
        Update: {
          id?: string;
          post_id?: string;
          tier2_result?: Json;
          confidence?: number;
          reviewer_id?: string | null;
          decision?: string | null;
          review_note?: string | null;
          created_at?: string;
          reviewed_at?: string | null;
        };
        Relationships: [];
      };
      ai_calls: {
        Row: {
          id: string;
          post_id: string | null;
          tier: number;
          model: string;
          prompt_version: string;
          input_tokens: number;
          output_tokens: number;
          cost_usd: number;
          latency_ms: number;
          request_payload: Json | null;
          response_payload: Json | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id?: string | null;
          tier: number;
          model: string;
          prompt_version: string;
          input_tokens: number;
          output_tokens: number;
          cost_usd: number;
          latency_ms: number;
          request_payload?: Json | null;
          response_payload?: Json | null;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string | null;
          tier?: number;
          model?: string;
          prompt_version?: string;
          input_tokens?: number;
          output_tokens?: number;
          cost_usd?: number;
          latency_ms?: number;
          request_payload?: Json | null;
          response_payload?: Json | null;
          error?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      check_required_extensions: {
        Args: Record<string, never>;
        Returns: Array<{
          extname: string;
          installed: boolean;
        }>;
      };
      pgmq_send: {
        Args: {
          queue_name: string;
          msg: Json;
        };
        Returns: number;
      };
      pgmq_read: {
        Args: {
          queue_name: string;
          vt: number;
          qty: number;
        };
        Returns: Array<{
          msg_id: number;
          read_ct: number;
          enqueued_at: string;
          vt: string;
          message: Json;
        }>;
      };
      pgmq_archive: {
        Args: {
          queue_name: string;
          msg_id: number;
        };
        Returns: boolean;
      };
      pgmq_create: {
        Args: {
          queue_name: string;
        };
        Returns: void;
      };
      find_similar_offer: {
        Args: {
          query_embedding: string;
          similarity_threshold: number;
          match_count: number;
        };
        Returns: Array<{
          id: string;
          similarity: number;
        }>;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

export type Source = Database['public']['Tables']['sources']['Row'];
export type Post = Database['public']['Tables']['posts']['Row'];
export type Offer = Database['public']['Tables']['offers']['Row'];
export type PostOffer = Database['public']['Tables']['post_offers']['Row'];
export type VerificationLog = Database['public']['Tables']['verification_log']['Row'];
export type HumanReviewItem = Database['public']['Tables']['human_review_queue']['Row'];
export type AiCall = Database['public']['Tables']['ai_calls']['Row'];
